-- Add metadata fields to books table for scanner enrichment
ALTER TABLE books ADD COLUMN narrator TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN genre TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN year INTEGER NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN series TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN has_cover INTEGER NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN duration INTEGER NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN chapter_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN metadata_source TEXT NOT NULL DEFAULT '';
ALTER TABLE books ADD COLUMN file_count INTEGER NOT NULL DEFAULT 0;
